version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: gestion_incidente
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: myadmin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup.dump:/docker-entrypoint-initdb.d/backup.dump  

  api:
    build: .  
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env 
    depends_on:
      - db

volumes:
  pgdata: 